### ISSUE TITLE
Suggestion: remove the upgrade command

### ISSUE THREAD

**Issue by wperron** [oslabs-beta/vno#50]
The upgrade subcommand is the only one that requires `--allow-run` but it can be removed and replaced in the docs with
```bash
deno install --reload -f -n vno https://deno.land/x/vno/dist/mod.ts
```

**Comment by jgrubb16** [comment]
Definitely. Thanks so much for the feedback.  Much appreciated!

**Comment by andrew-rehrig** [comment]
Removed upgrade command.
