### ISSUE TITLE
Single-line comments cause syntax error in built JS

### ISSUE THREAD

**Issue by danopia** [oslabs-beta/vno#53]
For example:
```vue
<script>
export default {
  name: 'app',
  // components: {HelloVno}
}
</script>
```

➡️ 

```javascript
const App = new Vue({template: `<div id="app">Hello!</div>`, name: 'app', // components: {HelloVno}});
```

```
> deno cache vno-build/build.js
error: Unexpected token `.`. Expected ... , *,  (, [, :, , ?, = or an identifier
at file:///tmp/tmp.7O0a68xw2G/test/vno-build/build.js:7:3
```

**Comment by buttercubz** [comment]
this happens because the compilation does not escape the characters but transfers them to Vue.component, a quick fix could be to use comments like this 
```js
<script>
export default {
  name: 'app',
  /* components: {HelloVno} */
}
</script>
```

```js
const App = new Vue({template: `<div id="app">Hello!</div>`, name: 'app', /* components: {HelloVno} */ });
``

**Comment by danopia** [comment]
So the minification can affect multiple different things then, such as:

```vue
<script>
export default {
  name: 'app',
  data: () => ({
    code: `#!/bin/sh
hostname
uptime
uname -a
`,
  }),
}
</script>
```

puts the whole string literal on line line:

```javascript
const App = new Vue({template: `<div id="app">Hello!</div>`, name: 'app', data: () => ({ code: `#!/bin/shhostnameuptimeuname -a`, }),});
```

The comment workaround is good, but I still wanted to file the recklessness of the current minifier

**Comment by buttercubz** [comment]
> 
> The comment workaround is good, but I still wanted to file the recklessness of the current minifier

I agree, I think that a lexical analysis of the code before the transformation would solve those kinds of problems

**Comment by andrew-rehrig** [comment]
Those are great points -- we have updated the parser to account for single-line comments now and we're looking into line break issue now.

**Comment by andrew-rehrig** [comment]
the comment issue has been looked at and updated -- i opened a new issue about the line breaks in the compilation. will close this current one now. 🌟

**Comment by mggower** [comment]
@danopia @buttercubz we just sent out a new release which will deal with the single line comment issue, it'll remove any cases out of the build altogether. This is a temporary fix, but aim to fix a lot of these issues. 

another note, based on a lot of feedback on naming conventions the path is now "deno.land/x/vno/install/vno.ts"

**Comment by danopia** [comment]
Sweet, thanks for the rapid attention on this!
