### ISSUE TITLE
gitignore

### ISSUE THREAD

**Issue by olof-nord** [oslabs-beta/vno#59]
Quick question, sorry if this is obvious.

But should the `vno-build` folder be added to .gitignore?

I understand it is the build output folder.

**Comment by buttercubz** [comment]
> Quick question, sorry if this is obvious.
> 
> But should the `vno-build` folder be added to .gitignore?
> 
> I understand it is the build output folder.

Sure, you can build again, but keep in mind that the main script where the components are compiled as well as the styles are hosted here

**Comment by olof-nord** [comment]
Many thanks for your quick reply!

Keeping versioning/git in mind, wouldnt checking in the compiled artifacts (js, css) basically mean I track automatically generated changes and effectively lead me to track changes twice?

For typescript workflows (as opposed to javascript), I see it as common to first require a build followed by a run, in contrast to with javascript where only the latter is required.

**Comment by mggower** [comment]
I think it is likely a good practice to gitignore the build dir, from experience there has been some unnecessary merge conflicts involved without.

Deno runs a typecheck automatically if any changes have been made to any connected files before runtime (and build in the case of vno) so i dont believe it would run any additional checks after the build if the server is run consecutively
