### ISSUE TITLE
switch to vue 3 compiler

### ISSUE THREAD

**Issue by buttercubz** [oslabs-beta/vno#61]
I was with a colleague working on making a port of the sfc compiler from vue 3 to deno and I think we have already achieved it, here is the [repository](https://github.com/crewdevio/vue-deno-compiler), I think all the current compiler problems will be a thing of the past

**Comment by mggower** [comment]
awesome, this is really great

**Comment by buttercubz** [comment]
I have a branch where I have been doing integration tests of the vue sfc compiler, the isolation problems disappear almost completely, and also the error detection improves a lot, on the other hand I have also been able to successfully integrate the support for typescript and scss outside out of the box, also the ability to load imports and intermediate code within a component

here is the branch in which I am doing the tests https://github.com/buttercubz/vno/tree/vue3-compiler

**Comment by mggower** [comment]
this looks very exciting, and a great step forward. I created a branch 'vue3Compiler', would you want to create a PR into that branch with this? I'd like to test it out

**Comment by buttercubz** [comment]
sure

**Comment by mggower** [comment]
I'd love to get this merged and released, is there any other version for posscss in the vue_sfc_compiler repo that will not log depreciated errors to the console ?

**Comment by buttercubz** [comment]
yes, I have pending to remove the deprecation warnings

**Comment by mggower** [comment]
Just merged and published the release!
