### ISSUE TITLE
Uncaught (in promise) NotFound: No such file or directory (os error 2)

### ISSUE THREAD

**Issue by JADSN** [oslabs-beta/vno#63]
When run:  `vno create app` and `vno run build `

![vno_create_error](https://user-images.githubusercontent.com/7506354/104451507-68f51880-5580-11eb-8cc3-54e5bdee1262.png)

**Comment by mggower** [comment]
I'm not sure why this is happening I'll take a look ASAP

**Comment by buttercubz** [comment]
@JADSN try this, `vno create app ....`, then `cd app`, `vno run build`

**Comment by JADSN** [comment]
> @JADSN try this, `vno create app ....`, then `cd app`, `vno run build`

This works, thanks.
