### ISSUE TITLE
Installing vno in windows 10 shows this error.

### ISSUE THREAD

**Issue by BroJenuel** [oslabs-beta/vno#75]
I tried installing the vno but it shows this error.

![image](https://user-images.githubusercontent.com/31676163/105322983-8c653680-5c04-11eb-914e-6a6b707c8815.png)

**Comment by mggower** [comment]
Have you upgraded Deno to 1.7?

**Comment by BroJenuel** [comment]
> Have you upgraded Deno to 1.7?

oh it seems choco has a version 1.6, so I uninstalled it and used the 
```pws
iwr https://deno.land/x/install/install.ps1 -useb | iex
```
to install it,
and now it works.. Thanks

**Comment by BroJenuel** [comment]
> Have you upgraded Deno to 1.7?

oh it seems choco has a version 1.6, so I uninstalled it and used the 
```pws
iwr https://deno.land/x/install/install.ps1 -useb | iex
```
to install it,
and now it works.. Thanks
